global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:8001']
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']