apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: docker.io/i20020309/weather-service-bot:latest
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: weather-secrets
              key: telegram-token
        - name: BACKEND_URL
          value: "http://backend:8000"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"