apiVersion: v1
kind: Secret
metadata:
  name: weather-secrets
type: Opaque
data:
  openweathermap-api-key: MjhhZTYwNTkxNmE3MjYxYTIwYWE5MzdlOWE0NDk2NTE=
  telegram-token: Nzk5OTk4NDc1OTpBQUhDY3ltSHVqMHNqcGthM1NiYVpLYzZFMHZqdWE1d2tzRQ==