name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Чекаут кода
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Установка Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      # 4. Аутентификация с Railway
      - name: Authenticate with Railway
        run: |
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV
          railway login --api-key ${{ secrets.RAILWAY_TOKEN }} || railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway whoami  # Проверка аутентификации

      # 5. Связывание проекта
      - name: Link Railway project
        run: railway link --project <your-railway-project-id>
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # 6. Установка переменных окружения
      - name: Set environment variables
        run: |
          echo "OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}" >> .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env

      # 7. Деплой всех сервисов
      - name: Deploy Backend
        run: railway up --service backend --dockerfile ./backend/Dockerfile --env .env

      - name: Deploy Frontend
        run: railway up --service frontend --dockerfile ./frontend/Dockerfile --env .env

      - name: Deploy Bot
        run: railway up --service bot --dockerfile ./bot/Dockerfile --env .env

      - name: Deploy Redis
        run: railway up --service redis --image redis:7

      - name: Deploy Prometheus
        run: railway up --service prometheus --image prom/prometheus:latest --env .env

      - name: Deploy Grafana
        run: railway up --service grafana --image grafana/grafana:latest --env .env

      - name: Deploy Redis Exporter
        run: railway up --service redis-exporter --image oliver006/redis_exporter:latest --env .env

      - name: Deploy cAdvisor
        run: railway up --service cadvisor --image gcr.io/cadvisor/cadvisor:latest --env .env

      # 8. Настройка переменных и зависимостей
      - name: Configure service variables
        run: |
          railway service variable set REDIS_HOST=redis --service backend
          railway service variable set REDIS_PORT=6379 --service backend
          railway service variable set BACKEND_URL=http://backend:8000 --service bot
          railway service variable set REDIS_HOST=redis --service bot
          railway service variable set REDIS_PORT=6379 --service bot
          railway service variable set REDIS_ADDR=redis:6379 --service redis-exporter

      # 9. Настройка конфигурации Prometheus
      - name: Configure Prometheus
        run: |
          railway service volume create --name prometheus-data --service prometheus
          railway service variable set PROMETHEUS_CONFIG_FILE=/etc/prometheus/prometheus.yml --service prometheus
          railway service volume mount --volume prometheus-data --path /prometheus --service prometheus
